import math
from pathlib import Path
from typing import TextIO

from apytypes._apytypes import APyFixedArray, APyFloatArray


def generate_rom(
    table: APyFixedArray | APyFloatArray,
    entity: str | None = None,
    address: APyFixedArray | APyFloatArray | None = None,
    input_register: bool = False,
    output_register: bool = False,
    file: TextIO | None = None,
) -> None:
    table = table.squeeze()
    if table.ndim != 1:
        raise TypeError("Can only create ROMs for 1D-tables.")

    n = table.shape[0]
    address_bits = (
        address.bits if address is not None else max(1, math.ceil(math.log2(n)))
    )
    entity = entity or f"ROM_{address_bits}"

    if file:
        _write_rom(
            file,
            table,
            n,
            address_bits,
            address,
            entity,
            input_register,
            output_register,
        )
    else:
        with Path(entity + ".spade").open("w") as f:
            _write_rom(
                f,
                table,
                n,
                address_bits,
                address,
                entity,
                input_register,
                output_register,
            )


def _int(width: int, value: int) -> int:
    return int(value) & ((1 << width) - 1)


def _write_rom(
    f: TextIO,
    table: APyFixedArray | APyFloatArray,
    n: int,
    address_bits: int,
    address: APyFixedArray | APyFloatArray | None,
    entity: str,
    input_register: bool,
    output_register: bool,
) -> None:
    table_values = table.to_bits()
    data_bits = table.bits
    pipeline_depth = int(input_register) + int(output_register)

    data_type = "int" if isinstance(table, APyFixedArray) else "uint"

    def data_value(value: int) -> int:
        value = _int(data_bits, value)
        if data_type == "int" and value >= (1 << (data_bits - 1)):
            value -= 1 << data_bits
        return value

    if address is None:
        address_values = range(n)
    else:
        address = address.squeeze()
        if address.shape != table.shape:
            raise TypeError(
                "table and address must have the same shape (after squeeze)"
            )
        address_values = address.to_bits()

    f.write(f"// {entity} generated by APyTypes\n\n")

    f.write(
        f"pipeline ({pipeline_depth}) {entity}"
        f"(clk: clock, address: uint<{address_bits}>) -> {data_type}<{data_bits}> {{\n"
    )

    if input_register:
        f.write("    reg;\n\n")

    f.write(f"    let data: {data_type}<{data_bits}> = match address {{\n")

    for i in range(n):
        a = _int(address_bits, address_values[i])
        d = data_value(table_values[i])
        f.write(f"        {a} => {d},\n")

    f.write("        _ => 0,\n")
    f.write("    };\n")

    if output_register:
        f.write("\n    reg;\n")

    f.write("\n    data\n")
    f.write("}\n")
