"""Generate Verilog/SystemVerilog for ROM lookup tables."""

from __future__ import annotations

import math
from pathlib import Path
from typing import TextIO

from apytypes._apytypes import APyFixedArray, APyFloatArray


def generate_rom(
    table: APyFixedArray | APyFloatArray,
    entity: str | None = None,
    address: APyFixedArray | APyFloatArray | None = None,
    input_register: bool = False,
    output_register: bool = False,
    systemverilog: bool = False,
    file: TextIO | None = None,
) -> None:
    """
    Generate Verilog/SystemVerilog for a ROM.
    """
    table = table.squeeze()
    if table.ndim != 1:
        raise TypeError("Can only create ROMs for 1D-tables.")

    number_of_table_values = table.shape[0]
    if address is not None:
        address_bits = address.bits
    else:
        address_bits = max(1, math.ceil(math.log2(number_of_table_values)))

    module = entity or f"ROM_{address_bits}"

    if file:
        _write_rom(
            file,
            table,
            number_of_table_values,
            address_bits,
            address,
            module,
            input_register,
            output_register,
            systemverilog,
        )
    else:
        filename = module + (".sv" if systemverilog else ".v")
        with Path(filename).open("w") as f:
            _write_rom(
                f,
                table,
                number_of_table_values,
                address_bits,
                address,
                module,
                input_register,
                output_register,
                systemverilog,
            )


def _bits_literal(width: int, value: int) -> str:
    masked = int(value) & ((1 << width) - 1)
    return f"{width}'b{masked:0{width}b}"


def _write_rom(
    f: TextIO,
    table: APyFixedArray | APyFloatArray,
    number_of_table_values: int,
    address_bits: int,
    address: APyFixedArray | APyFloatArray | None,
    module: str,
    input_register: bool,
    output_register: bool,
    systemverilog: bool,
) -> None:
    table_values = table.to_bits()
    data_bits = table.bits

    if address is None:
        address_values = range(number_of_table_values)
    else:
        address = address.squeeze()
        if address.shape != table.shape:
            raise TypeError(
                "table and address must have the same shape (after squeeze)"
            )
        address_values = address.to_bits()

    needs_clk = input_register or output_register
    f.write(f"// {module} generated by APyTypes\n")

    if systemverilog:
        clk = "input logic clk,\n" if needs_clk else ""
        f.write(
            f"""module {module} (
    {clk}    input logic [{address_bits - 1}:0] address,
    output logic [{data_bits - 1}:0] data
);

  logic [{data_bits - 1}:0] data_comb;
"""
        )
    else:
        clk = "input wire clk,\n" if needs_clk else ""
        data_decl = "output reg" if output_register else "output wire"
        f.write(
            f"""module {module} (
    {clk}    input wire [{address_bits - 1}:0] address,
    {data_decl} [{data_bits - 1}:0] data
);

  reg [{data_bits - 1}:0] data_comb;
"""
        )

    if input_register:
        kind = "logic" if systemverilog else "reg"
        f.write(
            f"""  {kind} [{address_bits - 1}:0] address_q;
  {"logic" if systemverilog else "wire"} [{address_bits - 1}:0] address_tmp;

  {"always_ff" if systemverilog else "always"} @(posedge clk) begin
    address_q <= address;
  end

  assign address_tmp = address_q;

"""
        )
    else:
        kind = "logic" if systemverilog else "wire"
        f.write(
            f"""  {kind} [{address_bits - 1}:0] address_tmp;

  assign address_tmp = address;

"""
        )

    f.write("  always_comb begin\n" if systemverilog else "  always @* begin\n")
    f.write(
        "    data_comb = 'x;\n"
        if systemverilog
        else f"    data_comb = {{{data_bits}{{1'bx}}}};\n"
    )
    f.write(
        "    unique case (address_tmp)\n"
        if systemverilog
        else "    case (address_tmp)\n"
    )

    f.writelines(
        f"      {_bits_literal(address_bits, address_values[i])}: "
        f"data_comb = {_bits_literal(data_bits, table_values[i])};\n"
        for i in range(number_of_table_values)
    )

    f.write(
        "      default: data_comb = 'x;\n"
        if systemverilog
        else f"      default: data_comb = {{{data_bits}{{1'bx}}}};\n"
    )
    f.write("    endcase\n")
    f.write("  end\n\n")

    if output_register:
        f.write(
            f"""  {"always_ff" if systemverilog else "always"} @(posedge clk) begin
    data <= data_comb;
  end

"""
        )
    else:
        f.write("  assign data = data_comb;\n\n")

    f.write("endmodule\n")
