name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
         apt-get install --yes lcov
         pip install gcovr
    - name: Install APyTypes
      run: |
        python -m pip install .[test]
    - name: Test with pytest
      run: |
        pytest
    - name: Format coverage data
       gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root .
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
